const express = require('express')
const listarCategorias = require('./controladores/categoria/listar')
const cadastrarUsuario = require('./controladores/usuario/cadastrar')
const validarCorpoRequisicao = require('./intermediarios/joi/validarSchema/validarCorpoRequisicao')
const { schemaCadastro, schemaLogin } = require('./intermediarios/joi/schemas/schemaUsuario')
const logarUsuario = require('./controladores/usuario/logar')
const autenticarTokenUsuarioLogado = require('./intermediarios/token/autenticarTokenUsuarioLogado')
const atualizarUsuario = require('./controladores/usuario/atualizar')
const detalharUsuario = require('./controladores/usuario/detalhar')
const schemaProduto = require('./intermediarios/joi/schemas/schemaProduto')
const cadastrarProduto = require('./controladores/produto/cadastrar')
const atualizarProduto = require('./controladores/produto/atualizar')
const validarIdProduto = require('./intermediarios/validacoes/params/validarIdProduto')
const validarParamsRequisicao = require('./intermediarios/joi/validarSchema/validarParamsRequisicao')
const { schemaQuery, schemaParams, schemaClienteId } = require('./intermediarios/joi/schemas/schemaParametros')
const detalharProduto = require('./controladores/produto/detalhar')
const listarProduto = require('./controladores/produto/listar')
const excluirProduto = require('./controladores/produto/excluir')
const cadastrarCliente = require('./controladores/cliente/cadastrar')
const validarEmailCpf = require('./intermediarios/validacoes/body/validarEmailCpf')
const schemaCadastroCliente = require('./intermediarios/joi/schemas/schemaCliente')
const atualizarCliente = require('./controladores/cliente/atualizar')
const validarIdCliente = require('./intermediarios/validacoes/params/validarIdCliente')
const listarClientes = require('./controladores/cliente/listar')
const detalharCliente = require('./controladores/cliente/detalhar')
const validarQueryRequisicao = require('./intermediarios/joi/validarSchema/validarQueryRequisicao')
const validarCategoriaId = require('./intermediarios/validacoes/body/validarCategoriaId')
const validarEmail = require('./intermediarios/validacoes/body/validarEmail')
const validarFiltroCategoriaId = require('./intermediarios/validacoes/query/validarFiltroCategoriaId')
const multer = require('./uploadsDeArquivos/multer')
const validarEmailSenha = require('./intermediarios/validacoes/body/validarEmailSenha')
const listarPedidos = require('./controladores/pedido/listar')
const cadastrarPedido = require('./controladores/pedido/cadastrar')
const validarExclusao = require('./intermediarios/validacoes/params/ValidarExclusao')
const schemaPedido = require('./intermediarios/joi/schemas/schemaPedido')
const validarClienteIdBody = require('./intermediarios/validacoes/body/validarClienteId')
const validarProdutoIdBody = require('./intermediarios/validacoes/body/validarProdutoId')

const rotas = express()

rotas.get('/categoria', listarCategorias);
rotas.post('/usuario', validarCorpoRequisicao(schemaCadastro), validarEmail, cadastrarUsuario)
rotas.post('/login', validarCorpoRequisicao(schemaLogin), validarEmailSenha, logarUsuario)

rotas.use(autenticarTokenUsuarioLogado);
rotas.get('/usuario', detalharUsuario)
rotas.put('/usuario', validarCorpoRequisicao(schemaCadastro), validarEmail, atualizarUsuario)

rotas.post('/produto', multer.single('produto_imagem'), validarCorpoRequisicao(schemaProduto), validarCategoriaId, cadastrarProduto)
rotas.put('/produto/:id', multer.single('produto_imagem'), validarParamsRequisicao(schemaParams), validarCorpoRequisicao(schemaProduto), validarIdProduto, validarCategoriaId, atualizarProduto)
rotas.get('/produto', validarQueryRequisicao(schemaQuery), validarFiltroCategoriaId, listarProduto)
rotas.get('/produto/:id', validarParamsRequisicao(schemaParams), validarIdProduto, detalharProduto)
rotas.delete('/produto/:id', validarParamsRequisicao(schemaParams), validarIdProduto, validarExclusao, excluirProduto)

rotas.post('/cliente', validarCorpoRequisicao(schemaCadastroCliente), validarEmailCpf, cadastrarCliente)
rotas.put('/cliente/:id', validarParamsRequisicao(schemaParams), validarIdCliente, validarCorpoRequisicao(schemaCadastroCliente), validarEmailCpf, atualizarCliente)
rotas.get('/cliente', listarClientes)
rotas.get('/cliente/:id', validarParamsRequisicao(schemaParams), validarIdCliente, detalharCliente)

rotas.get('/pedido', validarQueryRequisicao(schemaClienteId), listarPedidos)
rotas.post('/pedido', validarCorpoRequisicao(schemaPedido), validarClienteIdBody, validarProdutoIdBody, cadastrarPedido)

module.exports = rotas